# Etapa 1: Build
FROM node:18 AS builder
WORKDIR /app

COPY package*.json ./
RUN npm install --force

COPY . .
RUN npm run build

# Etapa 2: Runtime
FROM node:18-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV PORT=3001

# Copia apenas o necessário da etapa de build
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/next.config.js ./next.config.js

# Reinstala apenas dependências de produção para reduzir tamanho da imagem
RUN npm install --omit=dev

EXPOSE 3001

CMD ["npm", "start"]